"""Parse `.aspec.py` files into a typed SpecModel via `ast` — never by import."""

from agentspec.parser.model import (
    RISK_RANK,
    AttrPath,
    DerivationAtom,
    DerivationBind,
    DerivationRow,
    FailurePolicy,
    FanOut,
    Filter,
    ImportRecord,
    PipelineBind,
    Rule,
    SchemaDef,
    SchemaField,
    SourceLoc,
    SpecConstant,
    SpecModule,
    TaskDef,
    TaskInput,
    ToolDecl,
    TypeExpr,
    UnknownAttr,
    ValueRef,
)
from agentspec.parser.parse import parse_file, parse_source

__all__ = [
    "RISK_RANK",
    "AttrPath",
    "DerivationAtom",
    "DerivationBind",
    "DerivationRow",
    "FailurePolicy",
    "FanOut",
    "Filter",
    "ImportRecord",
    "PipelineBind",
    "Rule",
    "SchemaDef",
    "SchemaField",
    "SourceLoc",
    "SpecConstant",
    "SpecModule",
    "TaskDef",
    "TaskInput",
    "ToolDecl",
    "TypeExpr",
    "UnknownAttr",
    "ValueRef",
    "parse_file",
    "parse_source",
]
